
name: PR Checks and Maintainer Approvals


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  require-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check required approvals
        uses: actions/github-script@v7
        with:
          github-token: '${{ secrets.PAT_GITHUB }}'
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const maintainers = ["MrImmortal09", "whilstsomebody", "0PrashantYadav0", "shuklamaneesh23", "gauravghodinde", "Robinaditya1045"];
            let approvals = new Set();

            reviews.forEach(review => {
              if (review.state === "APPROVED" && maintainers.includes(review.user.login.trim())) {
                approvals.add(review.user.login.trim());
              }
            });

            if (approvals.size < 1) {
              core.setFailed(`At least 1 maintainer approval is required. Currently approved by: ${Array.from(approvals).join(', ') || 'none'}`);
            }
